### ISSUE TITLE
不停闪退，根本没办法使用

### ISSUE THREAD

**Issue by Freemante** [kaich/FantasyPass#1]
iphonex，ios11.4.1
根本就打不开，打开就闪退

**Comment by kaich** [comment]
@Freemante 具体哪个步骤闪退，具体一点， 方便修复问题.. 我自己用没有闪退，其它人都没有反馈闪退情况。

**Comment by Freemante** [comment]
App Store 安装完毕一切正常。
开始调用Onedrive接口，同步keepass 2.x数据库，一切ok，可以打开，使用也没用问题
iPhone切换到主页或者其他程序后，再次打开FantasyPass，出现程序运行的画面（锁孔那个背景的）之后自动退出运行，APP就再也打不开了

我的QQ/Wechat号都是 5441 8600，一会儿录屏给你看看

**Comment by Freemante** [comment]
录了一段，放到百度云里了
时间太短等不到FantasyPass重新加载就杀了一下进程
链接: https://pan.baidu.com/s/1S5PYUmNLdBkJTR4QhNgJtw 密码: ritu
7天有效期

**Comment by kaich** [comment]
等下个版本，确认了修复问题再关闭！

**Comment by kaich** [comment]
已解决！
