### ISSUE TITLE
使用ChaCha20加密算法后应用崩溃

### ISSUE THREAD

**Issue by Felix2yu** [kaich/FantasyPass#2]
若使用ChaCha20加密算法，会导致只能在最外层下载，进入密码库后无法同步，并且过几秒后闪退。

版本：2.1
同步方式：坚果云

**Comment by kaich** [comment]
你好算法这块一直采用默认的在测试，下个版本我会测试改变加密算法的问题。为了保证可用的情况下，请暂时先切换到默认算法吧。

**Comment by kaich** [comment]
@Felix2yu 你提供下你能测试出崩溃的模拟数据库，我自己测试时没有任何问题的，无法重现你的问题。可以加群：831063212

**Comment by Felix2yu** [comment]
我改成AES后就好了，尝试新建了一个空库，也无法复现，挺奇怪的。
还碰到几个问题：
1、应该是「密钥」，而不是「秘钥」
2、导入通讯录闪退（不知道是不是因为iOS 12.1）
3、合并库之后底部那个提示框中的时间是UTC的，并没有根据时区来显示。

**Comment by kaich** [comment]
好的👌， 非常感谢反馈，细节方面会逐步优化的！
