### ISSUE TITLE
无法打开数据库直接闪退

### ISSUE THREAD

**Issue by ifoot** [kaich/FantasyPass#3]
无法打开数据库,输入密码直接闪退,keepass touch和strongbox可以打开使用

**Comment by kaich** [comment]
第一次用还是后来崩溃？ 

看看是不是这个问题，如果可以，可以附上出问题的测试数据库，我这里测试不出来！

另外可以参考下这个：https://github.com/kaich/FantasyPass/issues/2#issue-369399524
