### ISSUE TITLE
同步后会删除用户自定义图标

### ISSUE THREAD

**Issue by MZLAKg2aGGFs8yi** [kaich/FantasyPass#4]
如果在另一客户端新建条目然后同步到ios上，新建条目的用户自定义图标就会被删除。

**Comment by kaich** [comment]
PC用的什么客户端？ @MZLAKg2aGGFs8yi

**Comment by MZLAKg2aGGFs8yi** [comment]
> PC用的什么客户端？ @MZLAKg2aGGFs8yi

KeepassXC mac版

**Comment by kaich** [comment]
@MZLAKg2aGGFs8yi 好的，下班晚上回去看看..  3.0也就这几天提交了

**Comment by kaich** [comment]
@MZLAKg2aGGFs8yi 昨晚已找到问题所在
