### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by MZLAKg2aGGFs8yi** [kaich/FantasyPass#5]
3.0在safari下通过键盘调出会闪退

**Comment by kaich** [comment]
自定义键盘还是什么？请详细描述。或者加群方便沟通

**Comment by MZLAKg2aGGFs8yi** [comment]
就是ios通用设置里的键盘 FantasyPassKeyboard。好像通过键盘调用都会闪退，FantasyPassKeyboard上点那个unlock it解锁后也会闪退，导致解锁无效。我升级到了12.1.2不过升级前就有这个问题。（iphone xs max）

**Comment by kaich** [comment]
方便的话，最好把崩溃文件发给我一下。我没有iphone xs max， 没法模拟定位！

**Comment by MZLAKg2aGGFs8yi** [comment]
崩溃文件是？

**Comment by kaich** [comment]
加下管我我们里面的qq群号，方便沟通
