### ISSUE TITLE
"Memory usage too high" when auto filling.

### ISSUE THREAD

**Issue by kissglay** [kaich/FantasyPass#9]
好像升了iOS14就开始出现这个问题，根本没法用了。我的是iphone XS Max. 应该还不至于内存不够用吧。我以前还另外买过一个KyPass 4. 用那个就根本没这个问题。
不知道是怎么一回事。

**Comment by kaich** [comment]
直接闪退么？ 数据库多大？

**Comment by kissglay** [comment]
![IMG_2056](https://user-images.githubusercontent.com/529385/97434120-84755d80-1959-11eb-8fe1-73f54315504d.jpg)
是自动填充的时候，解锁数据库，马上就闪退，会出现这个。普通打开是正常的，没问题。
数据库大小2.08MB。
这是KeePass上的数据库设置，这个设置很多年没变过了。不过我是使用了不少"Templates"的，也就是那个"Teamplates for Keepass"的plugin。不知道和这个有没有关系。不过记得iOS14以前是没这个状况的。
![2020-10-28_20 12 18 094_KeePass_Database_Settings](https://user-images.githubusercontent.com/529385/97434406-efbf2f80-1959-11eb-9ccd-067158efad36.png)

**Comment by kaich** [comment]
优化图标，把数据库优化小点试试。

**Comment by kaich** [comment]
奇密数据库设置里面有这个功能，优化下试试看...

**Comment by kissglay** [comment]
这个用过了 "Optimize duplicate icons", 没有用。
我的Entry中的关于TOTP密钥的有两条，一条是KeePass上那个"Tray TOTP" plugin用的，还有个是KyPass这个iOS的App使用的，不知道和这个有没有关系。但感觉不是这个问题，iOS13的时候没出现过这种情况。
![2020-10-30_13 50 26 052](https://user-images.githubusercontent.com/529385/97666090-e350e900-1ab7-11eb-8aa3-ebe579acecf2.png)
但是我用KyPass就很正常，没问题。软件需要优化？

**Comment by kaich** [comment]
把你的数据库设置截图发上来看看，如果不是设置问题，那软件确实要底层进行优化了。

**Comment by kissglay** [comment]
我记得就改过一个KDF的iterations.
![2020-10-30_19 18 17 811_KeePass_Database_Settings](https://user-images.githubusercontent.com/529385/97699563-4efd7b00-1ae5-11eb-90d7-7d91ea42bac5.png)
![2020-10-30_19 18 23 171_KeePass_Database_Settings](https://user-images.githubusercontent.com/529385/97699570-50c73e80-1ae5-11eb-96c2-f92483ca75b4.png)
![2020-10-30_19 18 27 226_KeePass_Database_Settings](https://user-images.githubusercontent.com/529385/97699571-515fd500-1ae5-11eb-9aa7-0f78786246f3.png)
![2020-10-30_19 18 30 654_KeePass_Database_Settings](https://user-images.githubusercontent.com/529385/97699572-515fd500-1ae5-11eb-8967-f07ed15481ae.png)
![2020-10-30_19 19 11 857_KeePass_Database_Settings](https://user-images.githubusercontent.com/529385/97699577-51f86b80-1ae5-11eb-93c5-0f1ce72381fb.png)

**Comment by kaich** [comment]
iterations 设置小一点试试：60000

**Comment by kissglay** [comment]
不行，试过了。

**Comment by kaich** [comment]
那估计只能等底层优化了，底层优化太花时间。有个库太耗内存，条目多了之后，导致程序占用内存过高被杀。

**Comment by kaich** [comment]
可以先用其他客户端。等8.7版本会针对这个问题，出个解决方案，能正常使用填充功能。

**Comment by kissglay** [comment]
好的。不急。慢慢改。

**Comment by kissglay** [comment]
更新到了8.8, 这个问题应该还是没有解决。
8.7开始，自动填充可以进FantasyPass选条目（有时候需要操作两三遍，第一遍可能会失败），虽然还是有内存使用过高的提示。但是有些App是不行的，比如TeamViewer，随便怎样都是提示内存占用过高直接跳出。

**Comment by kissglay** [comment]
多加了两三条条目以后就变得和以前一样，彻底无法自动填充了……
看来不彻底优化是根本没办法用

**Comment by kaich** [comment]
总共多少条数据？数据库多大？

**Comment by kaich** [comment]
等下个版本，加了一个开关。应该可以用。

**Comment by kissglay** [comment]
> 总共多少条数据？数据库多大？

496条，2.16M

**Comment by kaich** [comment]
@kissglay 更新到8.9版本，打开极速填充
